#manual config
FROM nginx:stable-alpine as app-stage
COPY /dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /app
COPY setup.sh ./setup.sh
RUN chmod +x ./setup.sh
RUN dos2unix ./setup.sh
EXPOSE 80
CMD ./setup.sh && nginx -g 'daemon off;'

# docker build -t ib-nasabah:3.0-bali -f Dockerfile .
# docker tag ib-nasabah:3.0-bali nexus.pactindo.com:8443/ebanking/bali/ib-nasabah:3.0-Bali

#jenkin config
# >>>>>>
# FROM node:14.0.0 as build-stage
# WORKDIR /app
# COPY package*.json ./
# RUN git config --global url.https://github.com/.insteadOf git://github.com/
# RUN npm install
# COPY . .
# RUN npm run build

# # app stage
# FROM nginx:stable-alpine as app-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# WORKDIR /app
# COPY setup.sh ./setup.sh
# RUN chmod +x ./setup.sh
# RUN dos2unix ./setup.sh
# EXPOSE 80
# CMD ./setup.sh && nginx -g 'daemon off;'