APPNAME := ibb
TAGDOCKER:= 1.6.9
PATHNEXUS:= bag/front-end/prod

.PHONY: node
node:
	npm run build

.PHONY: docker
docker:
	npm run build
	docker build -t $(APPNAME):$(TAGDOCKER) .
	docker tag $(APPNAME):$(TAGDOCKER) nexus.pactindo.com:8443/$(PATHNEXUS)/$(APPNAME):$(TAGDOCKER)
	docker push nexus.pactindo.com:8443/$(PATHNEXUS)/$(APPNAME):$(TAGDOCKER)